### ISSUE TITLE
Using MIT License sscs-parser is reported to use incaompatible license

### ISSUE THREAD

**Issue by mark-herrmann** [thenativeweb/roboter#986] opened 2023-01-06 13:45 UTC
When using MIT as license for own project, roboter reports scss-parser to using an incompatible license.

Report: Running license check...
  Package      Version  License                Path                                                
  ───────────  ───────  ─────────────────────  ────────────────────────────────────────────────────
  scss-parser  1.0.6    SEE LICENSE IN README  /.../node_modules/scss-parser
▻ There are incompatible dependencies.
✗ License check failed.

checking the package-lock.json, scss-parser seems to be a peer dependency of package deps, which is a dependency of Roboter.

This are the licenses listed in my licenseCheck.json file:
    "0BSD",
    "Apache-2.0",
    "Artistic-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC-BY-3.0",
    "CC-BY-4.0",
    "CC0-1.0",
    "MIT",
    "ISC",
    "Python-2.0",
    "Unlicense"

Is the license of scss-parser indeed incompatible with MIT license?
Yes: I will open an issue on deps, since they are also using an MIT License. Maybe roboter should ignore deps package until it's fixed.
No: Roboter is mis-detecting and this should be fixed or a license is missing in licenseCheck.json (what would be the correct name for it?).

For now i will skip the license check on my qa workflow, until it's fixed or i have any guidance on this issue.

Thanks for any help with this issue.

To reproduce:
Initialize a new project (npm init)
Install roboter
Run Roboter license check

**Comment by goloroden** [comment] 2023-01-06 14:08
The license is not provided as a valid SPDX expression in the scss-parser package. Hence they need to fix this. roboter is working correctly here.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Mark Herrmann ***@***.***>
Gesendet: Friday, January 6, 2023 2:46:09 PM
An: thenativeweb/roboter ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [thenativeweb/roboter] Using MIT License sscs-parser is reported to use incaompatible license (Issue #986)


When using MIT as license for own project, roboter reports scss-parser to using an incompatible license.

Report: Running license check...
Package Version License Path
─────────── ─────── ───────────────────── ────────────────────────────────────────────────────
scss-parser 1.0.6 SEE LICENSE IN README /.../node_modules/scss-parser
▻ There are incompatible dependencies.
✗ License check failed.

checking the package-lock.json, scss-parser seems to be a peer dependency of package deps, which is a dependency of Roboter.

This are the licenses listed in my licenseCheck.json file:
"0BSD",
"Apache-2.0",
"Artistic-2.0",
"BSD-2-Clause",
"BSD-3-Clause",
"CC-BY-3.0",
"CC-BY-4.0",
"CC0-1.0",
"MIT",
"ISC",
"Python-2.0",
"Unlicense"

Is the license of scss-parser indeed incompatible with MIT license?
Yes: I will open an issue on deps, since they are also using an MIT License. Maybe roboter should ignore deps package until it's fixed.
No: Roboter is mis-detecting and this should be fixed or a license is missing in licenseCheck.json (what would be the correct name for it?).

For now i will skip the license check on my qa workflow, until it's fixed or i have any guidance on this issue.

Thanks for any help with this issue.

To reproduce:
Initialize a new project (npm init)
Install roboter
Run Roboter license check

**Closed** 2023-01-06 14:09 UTC
