### ISSUE TITLE
bot analyze does not handle multiple .eslintrc.json files

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#44] opened 2017-07-12 11:48 UTC
I started to create different .eslintrc.json files in my module:

`/.eslintrc.json`    - holding the main project configuration
`/tools/.eslintrc.json`    - holding some specifics that apply to the 'tools' folder only (disabling no-console and no-process-exit)

this is done according to the eslint documentation:
http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

now, running eslint manually or by the editor-integration, this works ok, applying the different rulesets.

but `bot analyze` obviously calls eslint in a different way, and applies the main project configuration only. that results in errors being thrown for the files in the tools directory.

**Comment by goloroden** [comment] 2017-07-12 14:42
Duplicate of #42, hence closed.

**Closed by goloroden** 2017-07-12 14:42 UTC
