### ISSUE TITLE
bot publish throws stacktrace on pending changes

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#23] opened 2016-08-17 06:50 UTC
bot publish with uncommitted changes ends with an output like:

[08:49:19] Error in plugin 'gitcheckpending'
Message:
    You have pending changes.
[08:49:19] '_release' errored after 9.49 s
[08:49:19] Error in plugin 'run-sequence(_gitcheckpending)'
Error
    at finish (/home/stheine/js/audit-server/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/home/stheine/js/audit-server/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/home/stheine/js/audit-server/node_modules/orchestrator/index.js:264:8)
    at /home/stheine/js/audit-server/node_modules/orchestrator/index.js:275:23
    at finish (/home/stheine/js/audit-server/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/stheine/js/audit-server/node_modules/orchestrator/lib/runTask.js:29:3)
    at Gulp.gulp.task.done (/home/stheine/js/audit-server/node_modules/roboter/lib/tasks/universal/gitcheckpending/index.js:16:14)
    at module.exports (/home/stheine/js/audit-server/node_modules/orchestrator/lib/runTask.js:34:7)

**Comment by goloroden** [comment] 2016-08-17 11:19
Thanks for reporting this issue, we'll have a look at it, and get back to you.

Please give us a little time for this.

**Comment by goloroden** [comment] 2016-11-15 09:46
Unfortunately, we can't do anything about this.

The problem is that in Gulp 3 it is not possible to run tasks sequentially out of the box, so you need to rely on an external package called [run-sequence](https://github.com/OverZealous/run-sequence). This package is meant as a temporary fix until Gulp 4 is being released, which will contain sequential execution out of the box.

Whenever the run-sequence package hits an error, [it forces printing the call stack](https://github.com/OverZealous/run-sequence/blob/v1.2.2/index.js#L56), and there is nothing you can do about it.

Hence I'm going to close this issue. Once Gulp 4 is out, we have to rewrite the entire wiring of roboter anyway, so hopefully then the problem won't arise any more.

Sorry for not having better news :-(

**Comment by goloroden** [comment] 2016-11-15 12:01
Incidentally, I found out that there is a replacement for run-sequence, which is called [gulp-sequence](https://www.npmjs.com/package/gulp-sequence).

Since they both use the same API, they can be exchanged arbitrarily. And the good news is: With gulp-sequence, it works as expected :-)

**Closed** 2016-11-15 12:02 UTC
Labels: Bug
